// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ZhuQueNGateInterface.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Author      : meiyu024717@gtjas.com
// Version     : ZQNGI_V0.1
// Update      : 2024/10/30
// Discription : ZhuQue Notification Gate Platform 朱雀通知网关平台功能号

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// 全量功能号
enum Com_Gtjaqh_Zhuque_Ngate_InterfaceType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// 占位
  case taskDefault // = 0

  /// 心跳 - 客户端沉默超过两个心跳周期，服务端主动断开链接
  case systemHeartbeat // = 1

  /// 申请 ZID
  case systemZidApply // = 2

  /// 基本信息采集，规定长连接建立后需首先调用
  case systemInfoRegister // = 10

  /// 主题订阅/取消订阅
  case subscribeTheme // = 50

  /// 消息回报
  case notify // = 7000
  case UNRECOGNIZED(Int)

  init() {
    self = .taskDefault
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .taskDefault
    case 1: self = .systemHeartbeat
    case 2: self = .systemZidApply
    case 10: self = .systemInfoRegister
    case 50: self = .subscribeTheme
    case 7000: self = .notify
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .taskDefault: return 0
    case .systemHeartbeat: return 1
    case .systemZidApply: return 2
    case .systemInfoRegister: return 10
    case .subscribeTheme: return 50
    case .notify: return 7000
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Com_Gtjaqh_Zhuque_Ngate_InterfaceType] = [
    .taskDefault,
    .systemHeartbeat,
    .systemZidApply,
    .systemInfoRegister,
    .subscribeTheme,
    .notify,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Com_Gtjaqh_Zhuque_Ngate_InterfaceType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "TASK_DEFAULT"),
    1: .same(proto: "SYSTEM_HEARTBEAT"),
    2: .same(proto: "SYSTEM_ZID_APPLY"),
    10: .same(proto: "SYSTEM_INFO_REGISTER"),
    50: .same(proto: "SUBSCRIBE_THEME"),
    7000: .same(proto: "NOTIFY"),
  ]
}
